### PR TITLE
Add Chocolatey package

### PR DESCRIPTION
**Pull request by kwilliams1987**
In draft until the package is approved.

https://chocolatey.org/packages/wowup

### CODE REVIEW

**Comment by jliddev** [comment]
How does this get updated?

**Comment by kwilliams1987** [comment]
Every day at 06:00 UTC a script is run via Github Actions to check for new releases.

You can see the source code here: https://github.com/kwilliams1987/chocolatey-packages/tree/master/manual/wowup

**Comment by kwilliams1987** [comment]
The package is now marked as trusted by Chocolatey, this means new versions will normally be published within an hour or so of being submitted.

**Comment by jliddev** [comment]
No sure what to do with this?

**Comment by kwilliams1987** [comment]
Just needs to be merged so the documentation is updated?

Today I fixed the package to use the 2.0.0 installer method.

**Pull request merged**
