### PR TITLE
Implemented a export and import of addon list

### PR DESCRIPTION
**Pull request by Urganot**
In the options page there now is the option to export a list of all installed addons. also there is a option to import a list.

I also improved the results when installing an addon via url in curse. #132

(new pull request because of master branch)

### CODE REVIEW

**Comment by grimothy-the-reaper** [comment]
@Urganot 
Good idea. Couple of suggestions:

1. Make the export dialog have a file type
2. Restrict the import to that file type
3. Pre-populate a name on export for the WoW build you are exporting from (e.g. pre-populate the export file name as "retail_addons.json")
4. Make the file export as XML or JSON instead of semi-colon delimited text

**Comment by Urganot** [comment]
@grimothy-the-reaper 
Those are good ideas.
I also want the export to be used as a list to send to friends. originally i only wanted to include the addon name. that was a very easily readable list. I had to include the link or a lot of addons wouldnt install. when using json, i fear it could scare some people away from using it. any idea?

**Comment by jliddev** [comment]
If you're interested you can take a look at re-creating such a feature for 2.0 off the electron branch as we will not be bringing major features into 1.x anymore.

**Comment by Urganot** [comment]
I have no experience with electron but will check it out

**Comment by jliddev** [comment]
Needs ported to 2.0

**Comment by BretFisher** [comment]
+1 for export/import to keep addons in sync across computers. Like ElvUI, this could be much simpler as a JSON or similar file rather than the idea of having an account with addon stored centrally.

**Pull request closed without merging**
