### PR TITLE
Strip analytics

### PR DESCRIPTION
**Pull request by samlitowitz**
It would be nice to not send my data to ~Google~ Microsoft. This PR removes the telemetry/analytics suite.

### CODE REVIEW

**Comment by linaori** [comment]
Which part of this code sends it to google exactly?
Have you tried turning the service off instead of removing it?

**Comment by samlitowitz** [comment]
> Which part of this code sends it to google exactly?

My apologies, it's going to/through Microsoft instead which I would also like to avoid.

> Have you tried turning the service off instead of removing it?

Yes, but removing it makes it a non-issue.

**Comment by linaori** [comment]
Considering the analytics is opt-in, i think it's a non-issue to begin
with. Afaik you're prompted to make a choice upon installing the app the
first time. If this is not the case, or even on by default, that's probably
a bug.

**Comment by samlitowitz** [comment]
> Considering the analytics is opt-in, i think it's a non-issue to begin
with. Afaik you're prompted to make a choice upon installing the app the
first time. If this is not the case, or even on by default, that's probably
a bug.

Understood. I will close this PR then.

**Pull request closed without merging**
