### PR TITLE
polish translation - Polski

### PR DESCRIPTION
**Pull request by nydas3k**
polish translation

"Polski"

### CODE REVIEW

**Comment by nydas3k** [comment]
100% done

**Comment by nydas3k** [comment]
100% done

**Comment by jliddev** [comment]
@nydas3k since this is a new language can you add the code and name to this list so it's selectable? 

https://github.com/WowUp/WowUp/blob/develop/wowup-electron/src/app/components/options/options-app-section/options-app-section.component.ts#L55

**Comment by nydas3k** [comment]
> @nydas3k since this is a new language can you add the code and name to this list so it's selectable?
> 
> https://github.com/WowUp/WowUp/blob/develop/wowup-electron/src/app/components/options/options-app-section/options-app-section.component.ts#L55

Done

**Pull request merged**
