### PR TITLE
feature suggestion:  long number format for 4-digits based number-counting countries.

### PR DESCRIPTION
**Pull request by soaakim**
Hi.
This patch is for languages that don't count the long number by three digits. 
For example, in East Asia, we count numbers by four digits. 
(ten thousand = 만 (korean), 万 (chinese/japanese))
thus, it's difficult to translate a download count in CJK language. 

The patch content "COMMON.DOWNLOAD_COUNT.DIGIT_ABBR_UNIT" in ko.json refers to the number of digits for counting. (3 for the Western, 4 for East Asia)
The "ABBR_SUFFIXES" is translations for the each units.

Thanks.

### CODE REVIEW

**Comment by jliddev** [comment]
Hmm would something like this work better ? i dont know Korean, but would something like this work ? allowing us to control the suffix per decimal place?

"e+9": "{count} 십억",
      "e+8": "{count} 일억",
      "e+7": "{count} 천만",
      "e+6": "{count} 백만",
      "e+5": "{count} 십만",
      "e+4": "{count} 만",
      "e+3": "{count} 천",
      "e+2": "{count} 백",
      "e+1": "{count}",

**Comment by soaakim** [comment]
Yep. That works, too.

My code was just intended to be like original codes. ( counting by specific number of digits )
It's ok implementing that way.

**Comment by jliddev** [comment]
Not a problem, just curious if we could keep it generic still and have it work

**Comment by jliddev** [comment]
Moving the changes to #440 as discussed

**Comment by jliddev** [comment]
looks like the changes got lost :/

**Pull request closed without merging**
