### PR TITLE
[2.x] added scaling to Options

### LINKED ISSUE #247: [Feature Request] Consume less vertical space per line
It would be great if the lines could be way smaller, like maximum half or better 1/3 of current.
Its alot of wasted blank space that makes me scroll like crazy.

Thank you.

### PR DESCRIPTION
**Pull request by strayge**
* added ability to change scaling via `Options` (#247 shows that hotkeys is not enough)
* decreased minimum scaling via `MouseWheel+Down` to 60%
* changed scaling step via `MouseWheel` to multiplier of 1.1 - now it has the same behavior as via `Ctrl+Up/Down`.

Fixes (partially) #247

image

### CODE REVIEW

**Comment by jliddev** [comment]
Something went a little odd for me on Mac 
Screen Shot 2020-11-01 at 9 08 39 PM

**Comment by linaori** [comment]
Would it be possible to add a zoom notification/indicator in or around the footer? The minimum scrolling for the mousewheel was set to 100% because otherwise there's no way of properly resetting it as you don't know what zoom you're on 😂

**Comment by strayge** [comment]
@linaori 
> there's no way of properly resetting it

in current version ctrl+0 resets zoom to 100%  
with this PR user also can set 100% in options

> you don't know what zoom you're on

with this PR current zoom shown in options (but now it updates only on app restart)

**Comment by linaori** [comment]
If ctrl+0 resets it, then I have no complains 😄

**Comment by Medoke** [comment]
@strayge check the PR for Russian translations on your branch ;)

**Comment by strayge** [comment]
@jliddev 
> Something went a little odd for me on Mac

looks like fixed

**Comment by jliddev** [comment]
We need to have a larger discussion about zooming first.

**Comment by jliddev** [comment]
So my goal is to hook the hotkeys, mouse wheel zoom, and this dropdown to the same value. 

The electron server zoom-changed event seems to work well. 

What will it take to fix the hotkeys and the dropdown in options to this same mechanism?

**Comment by strayge** [comment]
The problem is keyboard shortcuts does not fire zoom-changed event, so i don't know way to change steps at this scaling.  
For now keyboard scaling uses this scales:
```
0.5787037037037037
0.633938145260609
0.6944444444444445
0.7607257743127308
0.8333333333333334
0.9128709291752769
1
1.0954451150103321
1.3145341380123985
1.44
1.5774409656148782
1.7279999999999998
1.8929291587378538
2.0736
2.2715149904854246
2.4883199999999994
2.7258179885825093
2.9859839999999993
3.270981586299011
```
Also our limits does not restrict it.

Mouse wheel and dropdown ways can be set to any values, as it totally controlled via code.

**Comment by strayge** [comment]
i've updated scale steps for mouse wheel and dropdown to the same as keyboard shortcuts uses.

**Comment by strayge** [comment]
@jliddev is anything else should I do with this PR?

**Comment by jliddev** [comment]
added #522 to support this PR

**Comment by strayge** [comment]
@jliddev so i can rebase it?

**Comment by jliddev** [comment]
Sure lets give it a shot

**Comment by strayge** [comment]
rebased

**Comment by jliddev** [comment]
Since we're working with the zoom levels, do you care if we try and add in storing the zoom level between sessions?

**Comment by strayge** [comment]
scaling factor already stored between sessions by electron

**Comment by jliddev** [comment]
So it does 👍

**Comment by jliddev** [comment]
Ok, i made some tweaks to handle the keyboard shortcuts the same way

RR8sUp0ygA

**Pull request merged**
