### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by Nils89**

### CODE REVIEW

**Comment by maestrohdude** [comment]
Line 356 ("PROTOCOL_DESCRIPTION") should say "...verarbeitet die eingehenden Anfragen" as opposed to "bearbeitet", right?

**Comment by Nils89** [comment]
> Line 356 ("PROTOCOL_DESCRIPTION") should say "...verarbeitet die eingehenden Anfragen" as opposed to "bearbeitet", right?

sounds better :) is changed

**Comment by maestrohdude** [comment]
I actually just saw as well line 373 it says "...dass du fortfahren möchten". Obviously möchten -> möchtest, but i think for consistency's sake the rest of the du's in the file have a capitalized "D".

End result: "...dass Du fortfahren möchtest"

**Comment by Nils89** [comment]
changed

**Review by jliddev — APPROVED** [review]

**Pull request merged**
