### PR TITLE
filter "get addons" by categories

### LINKED ISSUE #73: Categorized "Get Addons"
It would be a cool feature to have a big addon database available inside the client with division by categories, downloads, endorcements etc.
Twitch has it but UX of it sucks.

### PR DESCRIPTION
**Pull request by strayge**
fix #73 

search filtered by selected category
image

top from selected category
image

### CODE REVIEW

**Comment by jliddev** [comment]
Im not sure about this, we dont want to bind ourselves too closely to curse with a feature like this. it needs an abstraction layer so we can apply it to our own provider

**Comment by strayge** [comment]
@jliddev but at this PR each provider already has its own categories.  

what another abstraction layer you want?

**Comment by jliddev** [comment]
It may get confusing once we add tags from our new provider, but maybe we will rework this whole screen a bit when that happens so maybe this is fine as is. lemme try it out

**Comment by jliddev** [comment]
Seems to work well, found this random issue 
yJBiD7saZR

**Comment by strayge** [comment]
fixed test, changed dropdown to bottom for prevent that issue.

**Comment by jliddev** [comment]
This works fine, we need to look into virtual rows for the table tho, cause it chugs on 400 results

**Comment by jliddev** [comment]
Probably want to look into this before we pull to 2.2

https://diprokon.github.io/ng-table-virtual-scroll/#/examples

**Comment by jliddev** [comment]
Do any providers besides curse have categories?

**Comment by strayge** [comment]
in PR I presumed all from TUKUI is "Unit Frames"

**Comment by jliddev** [comment]
Hand merged this into develop

**Pull request closed without merging**
