### PR TITLE
Add Flatpak Support

### LINKED ISSUE #528: [Feature] Flatpak Packaging
First of all, thanks a ton for creating WowUp! This issue is part feature request, part question regarding whether you would accept contributions adding this.

**Is your feature request related to a problem? Please describe.**

Currently WowUp is packaged on Linux using the AppImage format. This format is great for cross-distribution distributables; however, has a not-so-great user experience for installation and integration into various desktops. Many Gnome-based Linux flavors are integrating Flatpak into their app centers and it would be awesome to be able to manage WowUp via the same method as other software on my system.

**Describe the solution you'd like**

Add WowUp to [Flathub](https://github.com/flathub/flathub/wiki/App-Submission) and make any CI changes necessary to support this new package format.

**Describe alternatives you've considered**

The current Linux distribution!

**Additional context**

- https://docs.flatpak.org/en/latest/electron.html
- https://github.com/electron-userland/electron-builder/issues/512

### PR DESCRIPTION
**Pull request by daegalus**
This PR adds flatpak building support. Closes #528 

Flatpak is very heavy on isolation, so some things work a bit differently, especially access to folders.

## Changes
- Add flatpak as a target
- Change icons from using the `.icns` to a folder of images, because Flatpak does not support 1024x1024 images.
  - Feel free to change the icon setup to your discretion, I was just trying to get it to work. I extracted the icons from the ICNS file. 
- Appropriate flatpak configuration that works (tested locally)
- Added `APPIMAGE=true` because I assume you do something custom for it that might be useful for Flatpaks, let me know if you want me to remove/change this or something else.

## General Info
- I included 2 folders that WoWUp will have access to. 
  - `~/Games` is where Lutris by default stores Wine Prefixes, and most people install WoW through Lutris.
  - `~/.wine/...` this is the default wine folder when not using prefixes, anyone doing a simple install might end up with WoW in this folder.
- For any non-standard folder, users will need to use Flatseal to add the appropriate folder to the list with their WoW installation.
- Wayland support is buggy with the tray icon. It loads fine, but if you `Close to Tray` and then select `Show` in the tray, it will crash. Does not happen on X11 mode, which is what the config is set to.
- For Gnome 40+ users, at least Gnome 42, the user needs to install `gnome-shell-extension-appindicator` and `libappindicator` and have the extension loaded. At least on Fedora this is needed.
- I upgraded Electron to 18.3.1, the latest in the 18 line, because there were a few Tray bugfixes that helped the tray work better.

## Deployment to Flathub
- This is something I am not sure how you wish to handle. To add your app to Flathub, you need to follow their submission process: https://github.com/flathub/flathub/wiki/App-Submission its fairly straightforward, just up to you if you want to embark on this process.
- Until then, just offering a Flatpak file should be sufficient for most, just wont have auto-updates.

### CODE REVIEW

**Comment by jliddev** [comment]
@Daegalus This needs to be looked at, it will not build in an Ubuntu build environment or GitHub Actions. With a non specific error ` ⨯ flatpak failed with status code 1  failedTask=build stackTrace=Error: flatpak failed with status code 1`

**Comment by Daegalus** [comment]
Oof sorry. I did all this on Fedora, wasn't expecting too large of a difference since Flatpaks tools and electron build are the core building tools.

I'll spin up an Ubuntu vm and get it working there. Sorry for not testing that.

I'll report back/open new PR when I figure out what's wrong.

**Comment by Daegalus** [comment]
@jliddev so I found the issue. The following needs to be run on the ubuntu install:

```
sudo apt install flatpak flatpak-builder
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
sudo flatpak install flathub org.freedesktop.Platform//21.08 org.freedesktop.Sdk//21.08 org.electronjs.Electron2.BaseApp//21.08 -y
```

I wanted to ask if you wanted me to make the changes to the Github Actions accordingly? I am not sure of there is an easy way to cache to keep build times similar. Right now they will get longer purely for since it has to download the base images for the flatpak.

**Comment by teian** [comment]
Is there any news about flatpak support? Would very much love this over AppImg

**Pull request merged**
